//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class modelo
    {
        public int Id_modelo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_marca { get; set; }
        public Nullable<int> id_tipo { get; set; }
    }
}
